/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula09Lab.View;

import Aula09Lab.Controller.UserController;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author rafss
 */
public class MenuUsuario extends javax.swing.JFrame {
    private final UserController controller = new UserController(this);
    /**
     * Creates new form CadastroUsuario
     */
    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelTabs = new javax.swing.JTabbedPane();
        panelCadastro = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        sobrenome = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        sexoPanel = new javax.swing.JPanel();
        labelSexo = new javax.swing.JLabel();
        radioMasculino = new javax.swing.JRadioButton();
        radioFeminino = new javax.swing.JRadioButton();
        buttonCadastra = new javax.swing.JButton();
        textFieldNome = new javax.swing.JTextField();
        textFieldCPF = new javax.swing.JTextField();
        textFieldSobrenome = new javax.swing.JTextField();
        textFieldIdade = new javax.swing.JTextField();
        panelProcura = new javax.swing.JPanel();
        labelProcurarCPF = new javax.swing.JLabel();
        textFieldCPFBuscar = new javax.swing.JTextField();
        buttonExibir = new javax.swing.JButton();
        scrollTexto = new javax.swing.JScrollPane();
        textAreaUsuarioInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar");

        nome.setText("Nome:");

        sobrenome.setText("Sobrenome:");

        idade.setText("Idade:");

        cpf.setText("CPF:");

        labelSexo.setText("Sexo:");

        radioMasculino.setText("Masculino");

        radioFeminino.setText("Feminino");

        javax.swing.GroupLayout sexoPanelLayout = new javax.swing.GroupLayout(sexoPanel);
        sexoPanel.setLayout(sexoPanelLayout);
        sexoPanelLayout.setHorizontalGroup(
                sexoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sexoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sexoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radioMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sexoPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        sexoPanelLayout.setVerticalGroup(
                sexoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sexoPanelLayout.createSequentialGroup()
                                .addComponent(labelSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioFeminino))
        );

        buttonCadastra.setText("Cadastra");
        buttonCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastraAction(evt);
            }
        });
        buttonExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExibirPorCPFAction(evt);
            }
        });

        radioMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeSexoAction(evt, true);
            }
        });

        radioFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeSexoAction(evt, false);
            }
        });
        
        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
                panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(sobrenome)
                                .addContainerGap(281, Short.MAX_VALUE))
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelCadastroLayout.createSequentialGroup()
                                                        .addGap(91, 91, 91)
                                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(panelCadastroLayout.createSequentialGroup()
                                                                                .addComponent(buttonCadastra)
                                                                                .addGap(103, 103, 103))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadastroLayout.createSequentialGroup()
                                                                                .addGap(43, 43, 43)
                                                                                .addComponent(textFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadastroLayout.createSequentialGroup()
                                                                                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(textFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadastroLayout.createSequentialGroup()
                                                                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(textFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(panelCadastroLayout.createSequentialGroup()
                                                                        .addComponent(sexoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(107, 107, 107))))
                                                .addGroup(panelCadastroLayout.createSequentialGroup()
                                                        .addGap(83, 83, 83)
                                                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(92, Short.MAX_VALUE)))
        );
        panelCadastroLayout.setVerticalGroup(
                panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(sobrenome)
                                .addContainerGap(233, Short.MAX_VALUE))
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(nome)
                                                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(textFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(idade)
                                                .addComponent(textFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cpf)
                                                .addComponent(textFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonCadastra)
                                        .addContainerGap(38, Short.MAX_VALUE)))
        );

        panelTabs.addTab("Usuario", panelCadastro);

        labelProcurarCPF.setText("Procurar por CPF: ");

        buttonExibir.setText("Exibir");

        textAreaUsuarioInfo.setColumns(20);
        textAreaUsuarioInfo.setRows(5);
        scrollTexto.setViewportView(textAreaUsuarioInfo);

        javax.swing.GroupLayout panelProcuraLayout = new javax.swing.GroupLayout(panelProcura);
        panelProcura.setLayout(panelProcuraLayout);
        panelProcuraLayout.setHorizontalGroup(
                panelProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProcuraLayout.createSequentialGroup()
                                .addGroup(panelProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelProcuraLayout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(buttonExibir))
                                        .addGroup(panelProcuraLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(panelProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(scrollTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panelProcuraLayout.createSequentialGroup()
                                                                .addComponent(labelProcurarCPF)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldCPFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelProcuraLayout.setVerticalGroup(
                panelProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProcuraLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(panelProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelProcurarCPF)
                                        .addComponent(textFieldCPFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonExibir)
                                .addGap(28, 28, 28)
                                .addComponent(scrollTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelTabs.addTab("Pesquisar", panelProcura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTabs)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastraAction(ActionEvent al){
        controller.cadastraUser();
    }

    private void buttonExibirPorCPFAction(ActionEvent al){
        controller.exibirUserPorCPF();
    }

    private void buttonChangeSexoAction(ActionEvent ae, boolean sexo){
        controller.changeSelectedSexo(sexo);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonCadastra;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel idade;
    private javax.swing.JButton buttonExibir;
    private javax.swing.JLabel labelProcurarCPF;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelProcura;
    private javax.swing.JScrollPane scrollTexto;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JTextArea textAreaUsuarioInfo;
    private javax.swing.JTextField textFieldCPFBuscar;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel nome;
    private javax.swing.JRadioButton radioFeminino;
    private javax.swing.JRadioButton radioMasculino;
    private javax.swing.JPanel sexoPanel;
    private javax.swing.JLabel sobrenome;
    private javax.swing.JTextField textFieldCPF;
    private javax.swing.JTextField textFieldIdade;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldSobrenome;
    // End of variables declaration


    public JTextField getTextFieldSobrenome() {
        return textFieldSobrenome;
    }

    public void setTextFieldSobrenome(JTextField textFieldSobrenome) {
        this.textFieldSobrenome = textFieldSobrenome;
    }

    public JTextField getTextFieldNome() {
        return textFieldNome;
    }

    public void setTextFieldNome(JTextField textFieldNome) {
        this.textFieldNome = textFieldNome;
    }

    public JTextField getTextFieldIdade() {
        return textFieldIdade;
    }

    public void setTextFieldIdade(JTextField textFieldIdade) {
        this.textFieldIdade = textFieldIdade;
    }

    public JTextField getTextFieldCPF() {
        return textFieldCPF;
    }

    public void setTextFieldCPF(JTextField textFieldCPF) {
        this.textFieldCPF = textFieldCPF;
    }

    public JLabel getSobrenome() {
        return sobrenome;
    }

    public void setSobrenome(JLabel sobrenome) {
        this.sobrenome = sobrenome;
    }

    public JPanel getSexoPanel() {
        return sexoPanel;
    }

    public void setSexoPanel(JPanel sexoPanel) {
        this.sexoPanel = sexoPanel;
    }

    public JRadioButton getRadioMasculino() {
        return radioMasculino;
    }

    public void setRadioMasculino(JRadioButton radioMasculino) {
        this.radioMasculino = radioMasculino;
    }

    public JRadioButton getRadioFeminino() {
        return radioFeminino;
    }

    public void setRadioFeminino(JRadioButton radioFeminino) {
        this.radioFeminino = radioFeminino;
    }

    public JLabel getNome() {
        return nome;
    }

    public void setNome(JLabel nome) {
        this.nome = nome;
    }

    public JLabel getLabelSexo() {
        return labelSexo;
    }

    public void setLabelSexo(JLabel labelSexo) {
        this.labelSexo = labelSexo;
    }

    public JTextField getTextFieldCPFBuscar() {
        return textFieldCPFBuscar;
    }

    public void setTextFieldCPFBuscar(JTextField textFieldCPFBuscar) {
        this.textFieldCPFBuscar = textFieldCPFBuscar;
    }

    public JTextArea getTextAreaUsuarioInfo() {
        return textAreaUsuarioInfo;
    }

    public void setTextAreaUsuarioInfo(JTextArea textAreaUsuarioInfo) {
        this.textAreaUsuarioInfo = textAreaUsuarioInfo;
    }

    public JTabbedPane getPanelTabs() {
        return panelTabs;
    }

    public void setPanelTabs(JTabbedPane panelTabs) {
        this.panelTabs = panelTabs;
    }

    public JScrollPane getScrollTexto() {
        return scrollTexto;
    }

    public void setScrollTexto(JScrollPane scrollTexto) {
        this.scrollTexto = scrollTexto;
    }

    public JPanel getPanelProcura() {
        return panelProcura;
    }

    public void setPanelProcura(JPanel panelProcura) {
        this.panelProcura = panelProcura;
    }

    public JPanel getPanelCadastro() {
        return panelCadastro;
    }

    public void setPanelCadastro(JPanel panelCadastro) {
        this.panelCadastro = panelCadastro;
    }

    public JLabel getLabelProcurarCPF() {
        return labelProcurarCPF;
    }

    public void setLabelProcurarCPF(JLabel labelProcurarCPF) {
        this.labelProcurarCPF = labelProcurarCPF;
    }

    public JButton getButtonExibir() {
        return buttonExibir;
    }

    public void setButtonExibir(JButton buttonExibir) {
        this.buttonExibir = buttonExibir;
    }

    public JLabel getIdade() {
        return idade;
    }

    public void setIdade(JLabel idade) {
        this.idade = idade;
    }

    public JLabel getCpf() {
        return cpf;
    }

    public void setCpf(JLabel cpf) {
        this.cpf = cpf;
    }

    public JButton getButtonCadastra() {
        return buttonCadastra;
    }

    public void setButtonCadastra(JButton buttonCadastra) {
        this.buttonCadastra = buttonCadastra;
    }
}
